name: Terraform Deployment

on: 
  workflow_dispatch:
    inputs:
      domain_name:
        description: The domain name for the website.
        required: true
        # Change to your domain name
        default: testdomain.net
      region: 
        description: AWS Region to deploy resources.
        required: true
        default: us-east-1
      destroy:
        description: Destroy the AWS Environment?
        required: true
        default: false
        type: boolean

jobs:
  terraform_execution:
    name: Execute terraform deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - uses: actions/checkout@v1

    - name: Verify Terraform version
      run: terraform --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Initialise Terraform & validate configuration
      run: |
        terraform init
        terraform validate

    - name: Deploy Terraform Environment
      if: ${{ !inputs.destroy }}
      working-directory: ./terraform
      run: terraform apply -auto-approve -input=false -var='domain_name=${{ inputs.domain_name }}' -var='region=${{ inputs.region }}' -var='zone_id=${{ secrets.ZONE_ID }}'

    - name: Destroy Terraform Environment
      if: ${{ inputs.destroy }}
      working-directory: ./terraform
      run: terraform destroy -auto-approve -input=false -var='domain_name=${{ inputs.domain_name }}' -var='region=${{ inputs.region }}' -var='zone_id=${{ secrets.ZONE_ID }}'