name: Website Deployment

on: 
  push:
    branches:
      - main
  
jobs:
  jekyll:
    name: Build Jekyll site & Deploy to S3 Bucket
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set-up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Jekyll install & compile
      run: | 
        gem install jekyll bundler
        bundle install
        bundle exec jekyll build
      working-directory: ./web

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    # Change below s3:// destination to your domain/bucket name
    - name: Sync Jekyll code to S3
      run: |
        aws s3 sync ./web/_site/ s3://www.huewood.net --delete